### ISSUE TITLE
maybe add description field to observations?

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-api#107]
linked to #104, should we add a description field to observation objects? this would help distinguish, e.g., one ghi observation at a site from another ghi observation at the same site

**Comment by lboeman** [comment]
I'm in favor of this. I think 'extra_parameters' serves as a structured text field, and a 'description' could be some human friendly text that we actually show on the dashboard and such.

**Comment by wholmgren** [comment]
Didn't we have description in the dashboard prototype and removed it for simplicity?
