### ISSUE TITLE
enable sharing of roles between organizations

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-api#118]
will require an admin to share a role with a specific user, then for that user to accept the role

**Comment by lboeman** [comment]
Create a new object type for permissions, which will be used to control CRUD operations on user -> role mappings. This will enable sharing roles outside of the organization, by not requiring permissions to update a user outside the organization to grant a role to the user. This will also allow either the admin or user to remove the role without allowing unnecessary access to either user.

**Comment by lboeman** [comment]
closed by #145
