### ISSUE TITLE
Objects/roles/permissions listings returned as strings

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-api#123]
Not sure what is causing this.
The `objects` dictionary on permisisons, the `permissions` dictionary on roles, and the `roles` listing on users are all serialized as string despite their schema defining them as `ma.Dict`.

**Comment by alorenzo175** [comment]
I think this is because those things are JSON strings from the database and they never get converted to dicts to then be jsonified by marshmallow. So, the solution should be to call ``json.loads`` on the appropriate key after calling the procedure in storage_Interface
