### ISSUE TITLE
report post documentation

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-api#147]
The report POST documentation and examples don't give me enough information to figure out how to format the request. https://api.solarforecastarbiter.org/#tag/Reports/paths/~1reports~1/post

@lboeman can you clarify this doc string?

**Comment by alorenzo175** [comment]
seems like it's taken care of now? https://dev-api.solarforecastarbiter.org/#tag/Reports/paths/~1reports~1/get

**Comment by alorenzo175** [comment]
Looks like the only missing piece is that the filters keys is not well documented. This probably just requires a change in the schema from a list of dicts to a list of a FilterParameter schema

**Comment by alorenzo175** [comment]
if filters need an update in the datamodel, do that first
