### ISSUE TITLE
cost metrics

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-api#157]
Also relates to dashboard and core but putting this here because I think the API/database considerations are most important.

Talked with @lboeman this morning about how we can implement cost metrics. 

* Constant value: Simple field in report form. Store value with report metadata. Limitations are obvious.
* Value for each hour (1-24): Could be 24 fields in report form that are then stored with report metadata. Could be pulled from an Observation that has only 24 values and for which date is ignored, but that sounds fragile. Maybe ultimately not so useful to the user, though. Average time of day pricing is often not accurate over periods of more than a few months. 
* Value for each datetime: Add `cost_metric` with `$/MW` units to allowable `Observation` variables. User uploads time series of $/MW like any other observation. User selects the observation in the report form. Arbiter resamples cost metrics as necessary. Questions: does the observation need to be associated with the same site as the error is applied to? Can a user associate a unique cost metric with each forecast/observation pair, or must the user choose a single cost metric to apply to all pairs?
* Value for each datetime, for different errors: User creates and uploads more than one cost metric Observation. Report form allows user to select multiple cost metric observations and specify the min/max errors that each should be applied to.

Maybe could do the constant value and value for each datetime for beta.

What do you think of these ideas @alorenzo175?

**Comment by alorenzo175** [comment]
> Also relates to dashboard and core but putting this here because I think the API/database considerations are most important.
> 
> Talked with @lboeman this morning about how we can implement cost metrics.
> 
>     * Constant value: Simple field in report form. Store value with report metadata. Limitations are obvious.
> 
:+1: 

>     * Value for each hour (1-24): Could be 24 fields in report form that are then stored with report metadata. Could be pulled from an Observation that has only 24 values and for which date is ignored, but that sounds fragile. Maybe ultimately not so useful to the user, though. Average time of day pricing is often not accurate over periods of more than a few months.
> 

agreed that storing in an Observation is fragile and not something I want to support.

>     * Value for each datetime: Add `cost_metric` with `$/MW` units to allowable `Observation` variables. User uploads time series of $/MW like any other observation. User selects the observation in the report form. Arbiter resamples cost metrics as necessary. 

I'm not so sure about resampling. I would prefer that the interval must match with the evaluation interval.

> Questions: does the observation need to be associated with the same site as the error is applied to? 

I don't think that is necessary although things like timezones might matter. In the long run it might make sense to have cost metrics be separate things in the db/datamodel from observations.

> Can a user associate a unique cost metric with each forecast/observation pair, or must the user choose a single cost metric to apply to all pairs?

Seems like it could be either, but maybe keep it simple to start and require a single metric for all.

>     * Value for each datetime, for different errors: User creates and uploads more than one cost metric Observation. Report form allows user to select multiple cost metric observations and specify the min/max errors that each should be applied to.
> 
> 
> Maybe could do the constant value and value for each datetime for beta.
> 
> What do you think of these ideas @alorenzo175?

**Comment by wholmgren** [comment]
maybe duplicate of https://github.com/SolarArbiter/solarforecastarbiter-core/issues/126

**Comment by wholmgren** [comment]
Aidan suggests supporting constant (not time varying) bands of $/MW errors. Seems like a powerful and straightforward extension of the simple constant values idea. Data would be stored with report and would not require datamodel/database changes.

**Comment by alorenzo175** [comment]
closed by #262
