### ISSUE TITLE
Remove migration 30

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-api#160]
Here is a list of permissions deleted by the admin permission removal, for consideration before we completely remove the migration:

| description                                         | action | object_type | applies_to_all | get_organization_name(organization_id) |
| Create Roles                                        | create | roles       |              1 | Organization 1                         |
| Create Permissions                                  | create | permissions |              1 | Organization 1                         |
| Read Users                                          | read   | users       |              1 | Organization 1                         |
| Read all users                                      | read   | users       |              1 | Forecast Provider A                    |
| Read all users                                      | read   | users       |              1 | Forecast Provider B                    |
| Read all users                                      | read   | users       |              1 | Utility X                              |
| Read Self User 0c90950a-7cca-11e9-a81f-54bf64606445 | read   | users       |              0 | Unaffiliated                           |
| Read Self User a30c116c-dfc1-11e9-bf08-0242ac120002 | read   | users       |              0 | Unaffiliated                           |
| Read Self User 4b436bee-8245-11e9-a81f-54bf64606445 | read   | users       |              0 | Unaffiliated                           |
| Read Self User 6b230ff0-8245-11e9-a81f-54bf64606445 | read   | users       |              0 | Unaffiliated                           |
| Read Self User 7475a52c-8245-11e9-a81f-54bf64606445 | read   | users       |              0 | Unaffiliated                           |
| Read Self User ef026b76-c049-11e9-9c7e-0242ac120002 | read   | users       |              0 | Unaffiliated                           |
| Read Roles                                          | read   | roles       |              1 | Organization 1                         |
| View plant x roles                                  | read   | roles       |              0 | Utility X                              |
| Read Forecaster A plant role                        | read   | roles       |              0 | Forecast Provider A                    |
| Read Forecaster B plant role                        | read   | roles       |              0 | Forecast Provider B                    |
| Read all roles                                      | read   | roles       |              1 | Forecast Provider A                    |
| Read all roles                                      | read   | roles       |              1 | Forecast Provider B                    |
| Read all roles                                      | read   | roles       |              1 | Utility X                              |
| Read User Role a379b258-dfc1-11e9-bf08-0242ac120002 | read   | roles       |              0 | Unaffiliated                           |
| Read User Role a37f6f5c-dfc1-11e9-bf08-0242ac120002 | read   | roles       |              0 | Unaffiliated                           |
| Read User Role a383bb21-dfc1-11e9-bf08-0242ac120002 | read   | roles       |              0 | Unaffiliated                           |
| Read User Role a388e654-dfc1-11e9-bf08-0242ac120002 | read   | roles       |              0 | Unaffiliated                           |
| Read User Role a38e0d08-dfc1-11e9-bf08-0242ac120002 | read   | roles       |              0 | Unaffiliated                           |
| Read User Role a3927ccb-dfc1-11e9-bf08-0242ac120002 | read   | roles       |              0 | Unaffiliated                           |
| Read roles                                          | read   | roles       |              1 | Organization 1                         |
| Read Permissions                                    | read   | permissions |              1 | Organization 1                         |
| View plant x permissions                            | read   | permissions |              0 | Utility X                              |
| Read Forecaster A Plant permissions                 | read   | permissions |              0 | Forecast Provider A                    |
| Read Forecaster B Plant permissions                 | read   | permissions |              0 | Forecast Provider B                    |
| Read all permissions                                | read   | permissions |              1 | Forecast Provider A                    |
| Read all permissions                                | read   | permissions |              1 | Forecast Provider B                    |
| Read all permissions                                | read   | permissions |              1 | Utility X                              |
| Update User                                         | update | users       |              1 | Organization 1                         |
| Update Roles                                        | update | roles       |              1 | Organization 1                         |
| Update Permissions                                  | update | permissions |              1 | Organization 1                         |
| Delete Roles                                        | delete | roles       |              1 | Organization 1                         |
| Delete Permissions                                  | delete | permissions |              1 | Organization 1                         |
| Role Granter                                        | grant  | roles       |              1 | Organization 1                         |
| Role Revoker                                        | revoke | roles       |              1 | Organization 1                         |

**Comment by alorenzo175** [comment]
What if we just remove all the special permissions for Organization 1 and (testing@solarforecastarbiter.org)? I think the grant, revoke, delete is not ideal

**Comment by lboeman** [comment]
I thought I understood what you meant here but just to make sure we're on the same page. Do you mean remove all of the grant, revoke and delete roles pertaining to users, roles and permissions for organization 1?

**Comment by alorenzo175** [comment]
I actually just meant remove all permissions above for Organization 1, but maybe you want to keep read on some things?
