### ISSUE TITLE
Users moved to organization are unreadable by admin.

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-api#162]
Since the trigger to update "applies_to_all" permissions fires when the object is inserted into the table. Moving a user from one organization to another doesn't add them to the 'read all users' permissions of the new organization.

**Comment by lboeman** [comment]
@alorenzo175 I was thinking this should be handled by an trigger on updates to the user table. Does that sound reasonable to you?

**Comment by alorenzo175** [comment]
yes

**Comment by lboeman** [comment]
closed by #163
