### ISSUE TITLE
The default create role needs update on reports

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-api#171]
Otherwise they cannot be generated and the permission  can't currently be added in the dashboard?

**Comment by alorenzo175** [comment]
Perhaps on the creation of a report, the creator is also granted update permissions on that single report. Otherwise if the user has create report, but not update on all reports, the report will never be generated by the backend.

**Comment by lboeman** [comment]
I like that idea. I overlooked update permissions on things other than rbac objects in the default roles. so maybe the write role has update? or it can be it's own role.

**Comment by alorenzo175** [comment]
Looks like this will also be an issue for adding and removing cdf singles
