### ISSUE TITLE
make uncertainty optional

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-api#234]
With the way we're using uncertainty in core and in the dashboard report form, I think it's reasonable to relax the requirement that users supply an uncertainty.

**Comment by lboeman** [comment]
Would a valid default be 0? I'm not sure how we would handle a null value here if report uncertainty is set to `observation_uncertainty`.

**Comment by wholmgren** [comment]
No, in the metrics modules there are different code paths for 0 and `None`. 

The core datamodel.Observation would need to be modified to `uncertainty: Union[float, None] = None`, but I don't think it would cause any issues with reports. The `__set_uncertainty__` function would still work as intended. So I think we'd just be looking at new tests.

@alorenzo175 am I missing anything?

**Comment by alorenzo175** [comment]
> @alorenzo175 am I missing anything?

Not as far as I can tell
