### ISSUE TITLE
Forecast Blueprint

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-api#29]
Implement /forecasts endpoints in forecasts blueprint. Schema should also be updated with proper validation. 

notes for validation:
will need to verify this, duration, and issue freq later 
and issue_time. probably easiest to use pandas timedeltas for the former three, and a time function for issue_time

_Originally posted by @alorenzo175 in https://github.com/SolarArbiter/solarforecastarbiter-api/pull/28_

**Comment by wholmgren** [comment]
issue_time or issue_time_of_day?

**Comment by lboeman** [comment]
Good catch, I've just updated this in #28 so that it is reflected in the rendered documentation for stakeholder feedback.

**Comment by lboeman** [comment]
closed by #37
