### ISSUE TITLE
Index Error when uploading empty forecast data.

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-api#304]
Arising from https://github.com/SolarArbiter/solarforecastarbiter-api/blob/36c01dc70e4df6659aab7bd2811bc8199b93e116/sfa_api/forecasts.py#L258. Probably best to delegate raising an error to https://github.com/SolarArbiter/solarforecastarbiter-api/blob/36c01dc70e4df6659aab7bd2811bc8199b93e116/sfa_api/utils/request_handling.py#L227.

**Comment by alorenzo175** [comment]
dup #300, but will leave this one open

**Comment by lboeman** [comment]
closed by #305
