### ISSUE TITLE
get obs/forecast data doesn't support csv

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-api#35]
Looks like get obs/forecast data currently only supports JSON. It should also support csv.

https://dev-api.solarforecastarbiter.org/#tag/Observations/paths/~1observations~1{obs_id}~1values/get

https://dev-api.solarforecastarbiter.org/#tag/Forecasts/paths/~1forecasts~1{forecast_id}~1values/get

**Comment by lboeman** [comment]
closed by #37
