### ISSUE TITLE
Working Test API from static content in demo module.

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-api#38]
- [x] create demo objects to act as static data store.
- [x] Make storage module to load and interact with static data store.
- [ ] Update dashboard to call API for data.

issues discovered while working on dashboard:
- [x] Observations lack `interval_length` field 
- [x] `site_id` stored as UUID when parsed by marshmallow. cast to string for storage.
- [x] parse and store time duration variables in minutes
- [x] don't allow duplicate timestamps in uploads.

**Comment by lboeman** [comment]
@alorenzo175  @wholmgren  I've found some more time validation that will need to be added to the API. I'm not sure what reasonable bounds should be for the forecast time duration variables. We're currently parsing time duration variables explicitly for %H:%M format.

- [ ] issue_time of day: are all values between 00:00 and 23:59 valid?
- [ ] interval_length and run_length: should not be 00:00 Are there other bounds?
- [ ] lead_time_to_start: This will probably need a different validator, as the current one cannot validate values  >23:59. Do we need lead time to be this granular or would a set of values be sufficient? 

These conditions should be added to tests as well as the integration tests #48

**Comment by wholmgren** [comment]
issue time of day: yes for now.

others: one option could be that the API requires all timedeltas in minutes and the dashboard does the conversion. I think we might have discussed that together at some point.

**Comment by lboeman** [comment]
> issue time of day: yes for now.
> 
> others: one option could be that the API requires all timedeltas in minutes and the dashboard does the conversion. I think we might have discussed that together at some point.

I see I misunderstood a comment in my last PR, I mistakenly changed the expected format of timedeltas to HH:MM. I thought we'd just be storing timedeltas in minutes, but I think that requiring users to post in minutes is a better solution. I'll update the API to accept integer timedeltas in minutes.

**Comment by alorenzo175** [comment]
Seems like enough of this has been implemented?

**Comment by lboeman** [comment]
Agreed.
