### ISSUE TITLE
JSON missing/null value parsing

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-api#47]
If we're expecting users to serialize missing or null values into JSON as the javascript `null` object, Flask will parse it into None and pandas into a NaN.
If we need to be more permissive with missing data in JSON, we'll have to find/replace accepted NaN values.

**Comment by alorenzo175** [comment]
I think requiring ``null`` for JSON is acceptable behaviour as long as it is documented.

**Comment by wholmgren** [comment]
Ok with me
