### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-api#48]
On top of existing Unit tests we need 'integration' tests to ensure the system functions as expected. the requests used to test the dev-storage backend #39 are a good place to start for these.

- [ ] storage creates a uuid for new metadata objects, adds 'Provider' field.

**Comment by alorenzo175** [comment]
I think a combination of the full api tests and core tests interacting with the dev api mostly cover this. Can revisit if needed
