### ISSUE TITLE
Set Proper API responses

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-api#59]
All endpoints should respond with:
- a 200 code when successful
- 401: unauthorized when a user is not logged in (this may need to be merged with 404 depending on if we require signup for public data.
- 400 when a logged in user has permissions to perform an action but the request is invalid for some other reason. This usually produces a meaningful error message.
- 404 User lacks permissions or the resource does not exist. This is so that users cannot discover resources they do not have access to.

**Comment by alorenzo175** [comment]
I think this just requires going through each function/tests and verifying this is implemented
