### ISSUE TITLE
missing values on marshmallow deserialize

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-api#79]
Many fields in the schema are not required but have no ``missing``or ``default`` values. We should probably set these fields so we know the once place where default values come in. The database storage_interface also won't work as is since the fields are not set at times.

**Comment by lboeman** [comment]
I believe this was closed in #92 ?

**Comment by alorenzo175** [comment]
Not quite done. Looks like reports has fields that could be missing, along with in a few other places

**Comment by alorenzo175** [comment]
certainly still some report fields outstanding
