### ISSUE TITLE
validate modelingparameters schema

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-api#80]
Should check what kind of tracking type is set and validate that the required fields for that tracking type are present

**Comment by lboeman** [comment]
As a note for when this issue gets fixed:
Nested schema missing values are not provided when the field is missing from the serialized data, i.e. a weather station with no `modeling_parameters` field. This then causes the storage interface to throw a key error. 
[Marshmallow issue 1042](https://github.com/marshmallow-code/marshmallow/issues/1042) provides some work-arounds such as setting passing `missing=dict` into ma.Nested.
