### ISSUE TITLE
Handle values updates

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-api#82]
Currently, inserting values with the same timestamps throws a 1062 duplicate primary key error. We may need to add `ON DUPLICATE KEY UPDATE` to the INSERT statements in the store procedures for forecasts, observations and cdf_forecasts.

**Comment by alorenzo175** [comment]
That brings up the question of if we should allow updating values at all. I thought we talked about not allowing overlap, but maybe that's wrong. @wholmgren ?

**Comment by wholmgren** [comment]
I think we need to support updating values in some situations. For example, user uploads data, data qualification toolkit identifies issues, user processes their data in a different way, reuploads data for the same period.

The rules about data involved in trials would be trickier. For example, perhaps a forecaster should be allowed to update a forecast until a certain time (I think these are sometimes referred to as gate times). One could require that the observation data remain fixed during the whole trial. On the other hand, I think some-to-most forecasters would prefer for their forecasts to be evaluated against as much good data as possible. That would mean allowing the possibility of updating it later on if/when observation bad data is submitted during the trial.
