### ISSUE TITLE
Deletion 404s

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-api#83]
Since mysql fails silently when something doesn't exist, we should check for this and return something. Currently, deleting an object or trying to delete a missing object returns a 200 and trying to delete something you don't have access to throws a 404.

**Comment by alorenzo175** [comment]
I don't quite understand. Seems to me that only deleting a valid object that the user has permission to delete returns 204. Otherwise you get a 404. Do you mean if a user has read access to the object but not delete, trying to delete the object should return something else?

**Comment by lboeman** [comment]
No it looks like you're right, perhaps I had something broken in my branch. I had added tests to check that attempting to delete non existent objects returned a 404, and they were breaking with a 200 status code. I'll add those tests back in.
